### ISSUE TITLE
FTP structure has changed on CDC server.

### ISSUE THREAD

**Issue by stuboo** [mirador/nhanes#2]
It appears that the FTP structure has changed rendering `getdata.py` and `download.py` useless.  If anyone has a fix, I'd love to see the changes merged.  This looks like an incredibly useful set of scripts otherwise.

**Comment by chanderson0** [comment]
+1 would love to be able to use this tool! I dug around in the FTP server and don't see these files anywhere...

**Comment by codeanticode** [comment]
Hi, thanks so much for the heads up and comments and sorry for the slow response! I have been busy with other project, but coming back to NHANES and [Mirador](https://github.com/mirador/mirador) shortly, so hopefully will be able to fix the scripts soon.

**Comment by codeanticode** [comment]
Done with https://github.com/mirador/nhanes/pull/3
